# Generated by Django 5.1 on 2024-11-09 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spycat",
            name="salary",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AlterField(
            model_name="spycat",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
    ]
