# Generated by Django 5.1 on 2024-11-09 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cat", "0002_alter_spycat_salary_alter_spycat_years_of_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "cat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="cat.spycat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                ("notes", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="mission.mission",
                    ),
                ),
            ],
        ),
    ]
