# Generated by Django 5.1 on 2024-11-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat", "0002_alter_spycat_salary_alter_spycat_years_of_experience"),
        ("mission", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="cat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cat.spycat",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="mission.mission",
            ),
        ),
    ]
